### ISSUE TITLE
Second Text popup hard to read.

### ISSUE THREAD

**Issue by zelint** [JoeRobich/fd-vsthemes#3]
VsDark.fdi
![untitled-1](https://cloud.githubusercontent.com/assets/4951458/9598328/969c2646-5047-11e5-83d0-d64371a08449.png)

**Comment by JoeRobich** [comment]
I opened a pull request to address this issue.

https://github.com/fdorg/flashdevelop/pull/865

**Comment by JoeRobich** [comment]
The pull request was merged. This should be fixed in the next release. Thanks for logging it.
